version: '3.8'

services:
  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: user-backoffice-dev
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env.development
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:5173']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Production service
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: user-backoffice-prod
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge
